packages:
  - ./
  - ./playground
  - ./test/fixtures/*
catalog:
  '@antfu/eslint-config': ^4.13.3
  '@antfu/ni': ^25.0.0
  '@cfworker/json-schema': ^4.1.1
  '@nuxt/devtools': ^2.4.1
  '@nuxt/eslint': ^1.4.1
  '@nuxt/eslint-config': ^1.4.1
  '@nuxt/kit': ^3.17.4
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.17.4
  '@nuxt/test-utils': ^3.19.1
  '@standard-community/standard-json': ^0.3.0
  '@standard-schema/spec': ^1.1.0
  '@types/node': latest
  '@typescript-eslint/parser': ^8.50.0
  '@typescript-eslint/rule-tester': ^8.50.0
  '@typescript-eslint/utils': ^8.50.0
  '@valibot/to-json-schema': ^1.0.0
  bumpp: ^10.1.1
  changelogen: ^0.6.1
  consola: ^3.4.0
  eslint: ^9.28.0
  eslint-plugin-format: ^1.0.1
  lint-staged: ^16.1.0
  nuxt: ^3.17.4
  simple-git-hooks: ^2.13.0
  typescript: ~5.8.3
  unbuild: ^3.5.0
  valibot: ^1.1.0
  vitest: ^3.2.0
  vue-tsc: ^2.2.10
  zod: ^4.2.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
